# -*- coding: utf-8 -*-
"""Trabajo_Integrador_M2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HCMfNqg_mRVLXNK7zKf4RRr76xunYbzN
"""

# ============================================================
# AGENTE DE GESTIÓN DE FALLAS DE MANTENIMIENTO
# Proyecto Integrador M2 – Hidrocarburos del Perú
# ============================================================
# If running interactively the magic install may work, but as a .py script use safe runtime install
def ensure_packages():
    try:
        import langchain
    except Exception:
        import subprocess, sys
        subprocess.check_call([
            sys.executable, "-m", "pip", "install",
            "langchain", "langchain-openai", "langgraph-checkpoint-postgres",
            "psycopg[binary,pool]==3.2.6", "pydantic", "fpdf", "pandas"
        ])

ensure_packages()

# ------------------------------------------------------------
# 1. Imports, configuración y APIKEY
# ------------------------------------------------------------
import os, datetime, pandas as pd
from fpdf import FPDF
from pydantic import BaseModel
from langchain.chat_models import init_chat_model
from langchain.agents import create_agent
from langchain_core.tools import tool
from langgraph.checkpoint.postgres import PostgresSaver
from psycopg_pool import ConnectionPool
from langchain.messages import HumanMessage, SystemMessage
from langchain.agents.middleware import AgentMiddleware, ModelRequest, ModelResponse, before_agent
import openai

# Cargar API Key
with open("/content/api_key.txt") as archivo:
    apikey = archivo.read().strip()
os.environ["OPENAI_API_KEY"] = apikey

# ------------------------------------------------------------
# 2. Cargar datos simulados
# ------------------------------------------------------------
# Ajusta el separador según tu archivo real: usa sep=';' si está separado por punto y coma
equipos = pd.read_csv("/content/equipos.csv", encoding='latin1', sep=';', header=0)
repuestos = pd.read_csv("/content/repuestos.csv", encoding='latin1', sep=';', header=0)

# ============================================================
# Middleware de Validación y Redirección con @before_agent
# ============================================================

@before_agent(can_jump_to=["end"])
def validar_reporte(state, runtime):
    """
    Middleware que valida ID y ubicación antes de que el agente procese el reporte.
    Si hay error, corta el flujo y devuelve mensaje de verificación.
    """
    # Extraer texto del usuario
    texto_usuario = ""
    for msg in state["messages"]:
        if msg.type == "human":
            texto_usuario = msg.content

    # Normalizar texto
    texto_usuario = texto_usuario.strip().upper()

    # Validar ID de equipo
    id_valido = None
    for eid in equipos["ID"].astype(str):
        eid_norm = eid.strip().upper()
        if eid_norm in texto_usuario:
            id_valido = eid
            break

    if not id_valido:
        return {
            "messages": [SystemMessage(content="⚠️ Error: El ID de equipo no es válido o no existe. Por favor verificar")],
            "jump_to": "end"
        }

    # Validar ubicación vinculada al ID
    ubicacion = str(equipos[equipos["ID"] == id_valido]["Ubicacion"].values[0]).strip().upper()
    if ubicacion not in texto_usuario:
        return {
            "messages": [
                SystemMessage(
                    content=f"⚠️ Error: La ubicación reportada no coincide con el ID {id_valido}.\n"
                            f"Reporte redirigido a verificación."
                )
            ],
            "jump_to": "end"
        }

    # Si todo está correcto, continuar flujo normal
    return None

# ------------------------------------------------------------
# 4. Middleware de Confirmación de Acciones Sensibles
# ------------------------------------------------------------
class ConfirmacionMiddleware(AgentMiddleware):
    """
    Middleware que confirma antes de generar órdenes inmediatas en criticidad alta.
    """
    def wrap_model_call(self, request: ModelRequest, handler: callable) -> ModelResponse:
        texto_usuario = ""
        for msg in request.messages:
            if msg.type == "human":
                texto_usuario = msg.content

        if "criticidad alta" in texto_usuario.lower():
            confirmacion = SystemMessage(
                content="⚠️ Confirmación requerida: ¿Desea generar la orden inmediata para criticidad alta?"
            )
            return ModelResponse(result=[confirmacion])

        return handler(request)

# ------------------------------------------------------------
# 5. Middleware de Fallback
# ------------------------------------------------------------
class FallbackMiddleware(AgentMiddleware):
    """
    Middleware que devuelve un mensaje seguro si el agente no puede resolver.
    """
    def wrap_model_call(self, request: ModelRequest, handler: callable) -> ModelResponse:
        try:
            return handler(request)
        except Exception:
            mensaje_fallback = SystemMessage(
                content="⚠️ No se pudo determinar la criticidad del equipo. Verifique el ID o la ubicación."
            )
            return ModelResponse(result=[mensaje_fallback])

# ------------------------------------------------------------
# 6. Herramientas del agente
# ------------------------------------------------------------
class ReporteFalla(BaseModel):
    id_equipo: str
    descripcion: str

@tool
def procesar_reporte(texto: str) -> dict:
    """Procesa el texto de un reporte de falla para extraer el ID del equipo y la descripción."""
    for eid in equipos["ID"]:
        if eid in texto:
            return {"id_equipo": eid, "descripcion": texto}
    return {"error": "ID no encontrado"}

@tool
def integrar_datos(id_equipo: str) -> dict:
    """Integra datos del equipo y sus repuestos basándose en el ID del equipo."""
    eq = equipos[equipos["ID"] == id_equipo].iloc[0]
    rep = repuestos[repuestos["ID_Equipo"] == id_equipo].iloc[0]
    return {
        "id_equipo": id_equipo,
        "nombre": eq["Nombre"],
        "ubicacion": eq["Ubicacion"],
        "criticidad": eq["Criticidad"],
        "historial": eq["Historial"],
        "repuesto": rep["Repuesto"],
        "stock": rep["Stock"],
        "tiempo_reposicion": rep["TiempoReposicion"]
    }

@tool
def evaluar_criticidad(datos: dict) -> dict:
    """Evalúa la criticidad de una falla y genera alertas preventivas si el stock es cero."""
    criticidad = datos["criticidad"]
    alerta = None
    if criticidad in ["Baja", "Media"] and datos["stock"] == 0:
        alerta = "⚠️ Esta falla podría volverse media en 1 semana (sin repuesto disponible)."
    return {"criticidad_final": criticidad, "alerta": alerta}

@tool
def generar_informe(datos: dict, decision: dict) -> str:
    """Genera un informe ejecutivo en formato PDF con los detalles de la falla y la decisión."""
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    criticidad_final = decision.get("criticidad_final", datos.get("criticidad", "No definida"))
    alerta = decision.get("alerta", "Ninguna")
    encabezado = f"Atención de falla del equipo {datos['id_equipo']} – {criticidad_final}"
    pdf.cell(200, 10, encabezado, ln=True, align="C")
    pdf.ln(10)
    pdf.multi_cell(0, 10, f"""
Empresa: Hidrocarburos del Perú
Equipo: {datos['nombre']}
Ubicación: {datos['ubicacion']}
Criticidad oficial: {datos['criticidad']}
Historial: {datos['historial']}
Repuesto: {datos['repuesto']} | Stock: {datos['stock']} | Tiempo reposición: {datos['tiempo_reposicion']}
Acción recomendada: Realizar el trabajo correctivo según la criticidad del equipo
Alerta preventiva: {alerta}
Fecha: {datetime.date.today()}
Responsable: Ingeniero de campo 1
""")
    nombre_pdf = f"informe_{datos['id_equipo']}.pdf"
    pdf.output(nombre_pdf)
    return f"Informe generado: {nombre_pdf}"

# ------------------------------------------------------------
# 7. Configuración de memoria (PostgresSaver)
# ------------------------------------------------------------
with open("/content/postgrest_bd.txt") as archivo:
  DB_URI = archivo.read()

connection_kwargs = {"autocommit": True, "prepare_threshold": 0}

# Initialize the ConnectionPool outside a 'with' statement to keep it open
pool = ConnectionPool(conninfo=DB_URI, max_size=20, kwargs=connection_kwargs)
checkpointer = PostgresSaver(pool)
# checkpointer.setup()  # Ejecutar solo la primera vez

# ------------------------------------------------------------
# 8. Creación del agente híbrido
# ------------------------------------------------------------
modelo = init_chat_model("openai:gpt-4.1", temperature=0)

agente_fallas = create_agent(
    model=modelo,
    tools=[procesar_reporte, integrar_datos, evaluar_criticidad, generar_informe],
    checkpointer=checkpointer,
    middleware=[validar_reporte, ConfirmacionMiddleware(), FallbackMiddleware()],
    system_prompt="""
    Eres un agente de gestión de fallas de mantenimiento.
    - Valida ID y ubicación antes de procesar.
    - Maneja errores y redirige flujo cuando falta información.
    - Confirma acciones sensibles en criticidad alta.
    - Procesa reportes caóticos de texto libre.
    - Consulta criticidad, historial y repuestos.
    - Evalúa criticidad dinámica y genera alertas preventivas.
    - Redacta informe ejecutivo breve en PDF estructurado.
    - Registra cada orden en memoria por equipo.
    """
)

# ------------------------------------------------------------
# 9. Ejemplo de flujo completo (demo)
# ------------------------------------------------------------
reporte = "La bomba EQA-1001 en Planta-Cusco está fallando, presión baja, no arranca."
config = {"configurable": {"thread_id": "my_first_thread"}}

resultado = agente_fallas.invoke({"messages": [HumanMessage(content=reporte)]}, config=config)
print(resultado["messages"][-1].content)